use_frameworks!

platform :ios, '9.0'

target 'ICP_Commons_iOS_Example' do
  pod 'ICP_Commons_iOS', :path => '../'

#  target 'ICP_Commons_iOS_Tests' do
#    inherit! :search_paths
#
#    pod 'Quick', '~> 2.2.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#
#    pod 'Nimble', '~> 8.0.0'
#  end
end
